// react-mod-fed/src/Counter.styles.tsx
import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  counter: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    minWidth: "300px",
    minHeight: "300px",
    border: "none",
    borderRadius: "16px",
    padding: "30px",
    background: "linear-gradient(145deg, #1a1a1a, #2a2a2a)",
    boxShadow:
      "0 10px 20px rgba(0, 0, 0, 0.3), inset 0 2px 0 rgba(255, 255, 255, 0.1)",
  },
  titleContainer: {
    width: "100%",
    marginBottom: "20px",
    padding: "10px 0",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    textAlign: "center" as const,
  },
  title: {
    fontSize: "1.8rem",
    fontWeight: "bold",
    margin: 0,
    color: "white",
    textShadow: "0 2px 4px rgba(0, 0, 0, 0.5)",
    letterSpacing: "1px",
    background: "linear-gradient(to right, #4361ee, #ef476f)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  countDisplay: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "150px",
    height: "150px",
    borderRadius: "50%",
    background: "linear-gradient(145deg, #222222, #1a1a1a)",
    boxShadow:
      "inset 0 4px 8px rgba(0, 0, 0, 0.5), 0 0 0 8px rgba(30, 30, 30, 0.7), 0 0 15px rgba(0, 0, 0, 0.5)",
    marginBottom: "30px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    position: "relative" as const,
  },
  count: {
    fontSize: "4rem",
    fontWeight: "bold",
    margin: 0,
    color: "white",
    textShadow: "0 2px 4px rgba(0, 0, 0, 0.5)",
  },
  buttonContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
    width: "100%",
  },
  incrementButton: {
    margin: 0,
    padding: "15px 20px",
    borderRadius: "30px",
    border: "none",
    backgroundColor: "#4361ee",
    color: "white",
    fontSize: "1.1rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow:
      "0 4px 8px rgba(67, 97, 238, 0.3), inset 0 2px 0 rgba(255, 255, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.1)",
    outline: "none",
    textShadow: "0 1px 2px rgba(0, 0, 0, 0.2)",
    letterSpacing: "0.5px",
  },
  decrementButton: {
    margin: 0,
    padding: "15px 20px",
    borderRadius: "30px",
    border: "none",
    backgroundColor: "#ef476f",
    color: "white",
    fontSize: "1.1rem",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow:
      "0 4px 8px rgba(239, 71, 111, 0.3), inset 0 2px 0 rgba(255, 255, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.1)",
    outline: "none",
    textShadow: "0 1px 2px rgba(0, 0, 0, 0.2)",
    letterSpacing: "0.5px",
  },
};

// solid-mod-fed/src/Counter.styles.tsx
import type { JSX } from "solid-js";

export const styles: Record<string, JSX.CSSProperties> = {
  counter: {
    display: "flex",
    "flex-direction": "column",
    "align-items": "center",
    "justify-content": "center",
    "min-width": "300px",
    "min-height": "300px",
    border: "none",
    "border-radius": "16px",
    padding: "30px",
    background: "linear-gradient(145deg, #1a2e1a, #2a3e2a)",
    "box-shadow":
      "0 10px 20px rgba(0, 0, 0, 0.3), inset 0 2px 0 rgba(200, 255, 200, 0.1)",
  },
  titleContainer: {
    width: "100%",
    "margin-bottom": "20px",
    padding: "10px 0",
    "border-bottom": "1px solid rgba(200, 255, 200, 0.1)",
    "text-align": "center",
  },
  title: {
    "font-size": "1.8rem",
    "font-weight": "bold",
    margin: 0,
    color: "white",
    "text-shadow": "0 2px 4px rgba(0, 0, 0, 0.5)",
    "letter-spacing": "1px",
    background: "linear-gradient(to right, #2ecc71, #4ade80)",
    "-webkit-background-clip": "text",
    "-webkit-text-fill-color": "transparent",
  },
  countDisplay: {
    display: "flex",
    "align-items": "center",
    "justify-content": "center",
    width: "150px",
    height: "150px",
    "border-radius": "50%",
    background: "linear-gradient(145deg, #1e2e1e, #1a2a1a)",
    "box-shadow":
      "inset 0 4px 8px rgba(0, 0, 0, 0.5), 0 0 0 8px rgba(30, 50, 30, 0.7), 0 0 15px rgba(0, 0, 0, 0.5)",
    "margin-bottom": "30px",
    border: "1px solid rgba(200, 255, 200, 0.05)",
    position: "relative",
  },
  count: {
    "font-size": "4rem",
    "font-weight": "bold",
    margin: 0,
    color: "white",
    "text-shadow": "0 2px 4px rgba(0, 0, 0, 0.5)",
  },
  buttonContainer: {
    display: "flex",
    "flex-direction": "column",
    gap: "15px",
    width: "100%",
  },
  incrementButton: {
    margin: 0,
    padding: "15px 20px",
    "border-radius": "30px",
    border: "none",
    "background-color": "#2ecc71",
    color: "white",
    "font-size": "1.1rem",
    "font-weight": "bold",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "box-shadow":
      "0 4px 8px rgba(46, 204, 113, 0.3), inset 0 2px 0 rgba(255, 255, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.1)",
    outline: "none",
    "text-shadow": "0 1px 2px rgba(0, 0, 0, 0.2)",
    "letter-spacing": "0.5px",
  },
  decrementButton: {
    margin: 0,
    padding: "15px 20px",
    "border-radius": "30px",
    border: "none",
    "background-color": "#27ae60",
    color: "white",
    "font-size": "1.1rem",
    "font-weight": "bold",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "box-shadow":
      "0 4px 8px rgba(39, 174, 96, 0.3), inset 0 2px 0 rgba(255, 255, 255, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.1)",
    outline: "none",
    "text-shadow": "0 1px 2px rgba(0, 0, 0, 0.2)",
    "letter-spacing": "0.5px",
  },
};
